version: "3.2"

services:
  hubot:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - '8080:8080'
    volumes:
      - ./external-scripts.json:/hubot/external-scripts.json
      - ./scripts:/hubot/scripts
